---
- name: Install libnotify (Debian/Ubuntu)
  package:
    name: libnotify-bin
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install libnotify (Arch)
  package:
    name: libnotify
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install libnotify (Fedora/RHEL)
  package:
    name: libnotify
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Copy notify-send-all script to /usr/local/bin
  copy:
    src: ./files/notify-send-all
    dest: /usr/local/bin/notify-send-all
    mode: '0755'
  become: true

- name: Send desktop notification
  command: >
    notify-send-all -t 10000 "{{ title }}" "{{ message }}"
  changed_when: false
